### ISSUE TITLE
FutureSupport.sequentialExecution does not do what it's name implies

### ISSUE THREAD

**Issue by jgordijn** [magneticio/vamp-common#1]
The name implies that the futures are run sequentially, but this is not the case. Futures run in seperate threads. This function implements the same functionality as Futures.sequence.

**Comment by tnolet** [comment]
@jgordijn were picking this up in the next release. Thanks for the effort!

https://github.com/magneticio/vamp/issues/70

**Comment by dragoslav** [comment]
Hi Jeroen, you are absolutely right. Thanks!
